phantom_low_p:
  - 0
  - 0
  - 71

phantom_high_p:
  - 180
  - 99
  - 255

inserter_low_p:
  - 16
  - 0
  - 0

inserter_high_p:
  - 180
  - 255
  - 46

tentacle_low_p:
  - 16
  - 0
  - 0
  
tentacle_high_p:
  - 180
  - 255
  - 46
