phantom_low_p:
  - 0
  - 0
  - 132

phantom_high_p:
  - 132
  - 80
  - 241

inserter_low_p:
  - 0
  - 62
  - 0

inserter_high_p:
  - 119
  - 255
  - 114

tentacle_low_p:
  - 76
  - 20
  - 30

tentacle_high_p:
  - 137
  - 124
  - 85