phantom_low_p:
  - 34
  - 0
  - 103

phantom_high_p:
  - 129
  - 123
  - 255

inserter_low_p:
  - 85
  - 85
  - 0

inserter_high_p:
  - 105
  - 255
  - 100

tentacle_low_p:
  - 85
  - 85
  - 0
  
tentacle_high_p:
  - 105
  - 255
  - 100