phantom_low_p:
  - 4
  - 0
  - 77

phantom_high_p:
  - 180
  - 134
  - 255

inserter_low_p:
  - 39
  - 0
  - 0

inserter_high_p:
  - 150
  - 255
  - 97

tentacle_low_p:
  - 39
  - 0
  - 0
  
tentacle_high_p:
  - 150
  - 255
  - 97
