phantom_low_p:
  - 0
  - 0
  - 71

phantom_high_p:
  - 180
  - 141
  - 255

inserter_low_p:
  - 20
  - 26
  - 0

inserter_high_p:
  - 154
  - 243
  - 49

tentacle_low_p:
  - 20
  - 26
  - 0

tentacle_high_p:
  - 154
  - 243
  - 49
