phantom_low_p:
  - 0
  - 0
  - 62

phantom_high_p:
  - 174
  - 56
  - 255

inserter_low_p:
  - 29
  - 38
  - 0

inserter_high_p:
  - 85
  - 255
  - 55

tentacle_low_p:
  - 29
  - 38
  - 0
  
tentacle_high_p:
  - 85
  - 255
  - 55