phantom_low_p:
  - 0
  - 0
  - 21

phantom_high_p:
  - 70
  - 126
  - 255

inserter_low_p:
  - 15
  - 0
  - 0

inserter_high_p:
  - 178
  - 255
  - 93

tentacle_low_p:
  - 0
  - 0
  - 0

tentacle_high_p:
  - 180
  - 255
  - 39
