phantom_low_p:
  - 0
  - 0
  - 123

phantom_high_p:
  - 171
  - 94
  - 255

inserter_low_p:
  - 0
  - 74
  - 0

inserter_high_p:
  - 180
  - 255
  - 52

tentacle_low_p:
  - 0
  - 74
  - 0
  
tentacle_high_p:
  - 180
  - 255
  - 52