phantom_low_p:
  - 0
  - 0
  - 0

phantom_high_p:
  - 132
  - 80
  - 241

inserter_low_p:
  - 57
  - 0
  - 0

inserter_high_p:
  - 121
  - 255
  - 112

tentacle_low_p:
  - 70
  - 56
  - 41

tentacle_high_p:
  - 115
  - 153
  - 115