phantom_low_p:
  - 0
  - 0
  - 77

phantom_high_p:
  - 111
  - 56
  - 255

inserter_low_p:
  - 81
  - 43
  - 0

inserter_high_p:
  - 114
  - 255
  - 71

tentacle_low_p:
  - 81
  - 43
  - 0
  
tentacle_high_p:
  - 114
  - 255
  - 71