phantom_low_p:
  - 19
  - 0
  - 68

phantom_high_p:
  - 180
  - 49
  - 255

inserter_low_p:
  - 19
  - 0
  - 0
  
inserter_high_p:
  - 180
  - 255
  - 50

tentacle_low_p:
  - 19
  - 0
  - 0
  
  
tentacle_high_p:
  - 180
  - 255
  - 50