phantom_low_p:
  - 0
  - 0
  - 79

phantom_high_p:
  - 169
  - 143
  - 255

inserter_low_p:
  - 43
  - 0
  - 0

inserter_high_p:
  - 175
  - 255
  - 79

tentacle_low_p:
  - 0
  - 0
  - 0

tentacle_high_p:
  - 180
  - 255
  - 39
