phantom_low_p:
  - 0
  - 0
  - 103

phantom_high_p:
  - 180
  - 93
  - 255

inserter_low_p:
  - 58
  - 0
  - 0

inserter_high_p:
  - 180
  - 255
  - 50

tentacle_low_p:
  - 58
  - 0
  - 0
  
tentacle_high_p:
  - 180
  - 255
  - 50