phantom_low_p:
  - 0
  - 0
  - 129

phantom_high_p:
  - 180
  - 94
  - 255

inserter_low_p:
  - 51
  - 49
  - 0

inserter_high_p:
  - 102
  - 255
  - 76

tentacle_low_p:
  - 51
  - 49
  - 0
  
tentacle_high_p:
  - 102
  - 255
  - 76