phantom_low_p:
  - 0
  - 0
  - 64

phantom_high_p:
  - 180
  - 146
  - 255

inserter_low_p:
  - 24
  - 0
  - 0

inserter_high_p:
  - 165
  - 255
  - 121

tentacle_low_p:
  - 24
  - 0
  - 0
  
tentacle_high_p:
  - 165
  - 255
  - 121
