phantom_low_p:
  - 10
  - 0
  - 85

phantom_high_p:
  - 120
  - 61
  - 255

inserter_low_p:
  - 23
  - 0
  - 0

inserter_high_p:
  - 144
  - 255
  - 67

tentacle_low_p:
  - 23
  - 0
  - 0
  
tentacle_high_p:
  - 144
  - 255
  - 67