phantom_low_p:
  - 35
  - 0
  - 74

phantom_high_p:
  - 171
  - 100
  - 255

inserter_low_p:
  - 27
  - 0
  - 0

inserter_high_p:
  - 110
  - 155
  - 90

tentacle_low_p:
  - 27
  - 0
  - 0
  
tentacle_high_p:
  - 110
  - 155
  - 90